# Homework 12/12 (2-14 encoding_E)

This is an homework for a neural network course offered by the master's class of the Department of IEM at the NCUT in the first semester of the 2024 academic year (113-1).

**Submitted by: 4B315021 詹家緯**

The codes can be viewed on GitHub: [https://github.com/chankai1016/113-1_Neural_Network/](https://github.com/chankai1016/113-1_Neural_Network)

## Code

In [9]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.metrics import confusion_matrix
import tensorflow as tf
from tensorflow.keras import layers, models

# 載入 iris 資料集
iris = load_iris()
X = iris.data  # shape: (150,4)
y = iris.target.reshape(-1,1)  # shape: (150,1)

# One-hot encode y (使用新版 sklearn 參數)
encoder = OneHotEncoder(sparse_output=False)
y_encoded = encoder.fit_transform(y)  # shape: (150,3)

# 分割資料集
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=42)

# 標準化特徵
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 建立 Keras 模型 (輸入4維特徵)
model = models.Sequential([
    layers.Dense(16, activation='relu', input_shape=(X_train.shape[1],)),
    layers.Dense(16, activation='relu'),
    layers.Dense(3, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# 訓練模型
model.fit(X_train, y_train, epochs=50, batch_size=8, verbose=0)

# 評估模型
train_loss, train_acc = model.evaluate(X_train, y_train, verbose=0)
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=0)
print("訓練正確率:", train_acc)
print("測試正確率:", test_acc)

# 混淆矩陣
y_pred_proba = model.predict(X_test)
y_pred = np.argmax(y_pred_proba, axis=1)
y_true = np.argmax(y_test, axis=1)
cm = confusion_matrix(y_true, y_pred)
print("混淆矩陣:\n", cm)

# 處理 7x9 pixel 資料 (共四組)
pixel_data = [
 [1,1,1,1,1,1,1,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,1,1,1,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,1,1,1,1,1,1,1],
 [1,1,1,1,1,1,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,1,1,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,1,1,1,1,1],
 [1,1,1,1,1,1,1,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,1,1,1,1,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,1,1,1,1,1,1,1],
 [1,1,1,1,1,1,1,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,1,1,1,1,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,1,0,0,0,0,1,1,1,1,1,1,1]
]

X_pixels = np.array(pixel_data)  # shape: (4,63)
print("Pixel 資料形狀:", X_pixels.shape)

# 若想用同一個模型預測需要相同的輸入維度(4維)，但 pixel_data 為63維，不相容。
# 因此無法直接將 X_pixels 丟入同一個 iris 模型做預測。
# 若要對 pixel 資料進行分析，需要建立一個有 input_shape=(63,) 的新模型並針對該任務進行訓練。


訓練正確率: 0.9583333134651184
測試正確率: 1.0
1/1 [==============================] - 0s 124ms/step
混淆矩陣:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Pixel 資料形狀: (4, 63)
